### ISSUE TITLE
Review Microtasks

### ISSUE THREAD

**Issue by vchrombie** [SourabhSaraswat-191939/GSoC-chaoss-microtasks#1]
Hi @SourabhSaraswat-191939, thanks for showing interest in applying for the GrimoireLab idea and working on the microtasks as a part of the GSoC program.

You can open an issue per microtask with the title `Review Microtask <num>` in this repository. The body could be empty or contain anything you want to share (pointers to code or documentation, comments, difficulties found) about the microtask. I can help with reviewing the microtasks and suggest some improvements.

Thanks!

**Comment by SourabhSaraswat-191939** [comment]
OK @vchrombie sure i will do this now .

**Comment by vchrombie** [comment]
Thanks for working on the microtasks, please make sure you submit the proposal on the GSoC website as well as add your entry in the governance repository before the deadline.
