### ISSUE TITLE
Review Microtasks 1

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [SourabhSaraswat-191939/GSoC-chaoss-microtasks#2]
If any data or information is required to mention in Microtask 1 other than i mentioned please notify me .

**Comment by vchrombie** [comment]
Hi @SourabhSaraswat-191939, it would be great if you can write a few steps on how did you set up the project and have you faced any errors. If yes, how did you fix them. You need not go into minute details, but a brief explanation or steps would be great.

**Comment by SourabhSaraswat-191939** [comment]
Thanks @vchrombie, surely i will do this as soon as possible .

**Comment by vchrombie** [comment]
LGTM :+1:
