### ISSUE TITLE
Review Microtasks 2

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [SourabhSaraswat-191939/GSoC-chaoss-microtasks#3]
Please review this microtask and if anything left please let me know .

**Comment by vchrombie** [comment]
Again, it would be great if you can explain the steps a little bit more.

**Comment by SourabhSaraswat-191939** [comment]
@vchrombie ,sure i will do this as soon as possible .

**Comment by vchrombie** [comment]
LGTM :+1:
